services:
  postgresql:
    container_name: mg_projects_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:11-alpine
    networks:
      - mg_projects
    ports:
      - 5432:5432
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql:/var/lib/postgresql/data

  elasticsearch:
    container_name: mg_projects_elasticsearch
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    networks:
      - mg_projects
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  minio:
    command: server /data
    container_name: mg_projects_minio
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    networks:
      - mg_projects
    ports:
      - 9000:9000
    volumes:
      - minio:/data

  opencpu:
    container_name: mg_projects_opencpu
    image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
    networks:
      - mg_projects
    ports:
      - 8004:8004
      - 8787:8787
    volumes:
      - ./opencpu/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./opencpu/ports.conf:/etc/apache2/ports.conf

version: "3.8"
volumes:
  elasticsearch:
  minio:
  postgresql:
